RegisterServerEvent("vh:enginehealth")
AddEventHandler("vh:enginehealth", function( ped)
		print("*********************** player -->" ..  ped)
		local v = GetVehiclePedIsUsing(ped)
		SetVehicleEngineCanDegrade(v, true)
		print("***********************degrade was called")
		local health = GetVehicleEngineHealth(v)
		print("engine health -> " .. health)
end)